### ISSUE TITLE
VA Quickstart Exists!

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/va-quickstart#1]
@dannychapman and @MarinaMartin Registered VA bower package is a now a thing!

It's a humble beginning. Currently only has one scss file and a dependency on foundation. If you run "bower install va-quickstart it will install foundation and that file. 

@dannychapman let's go through and add all of the files it should include to be most useful. I started initially to include everything, but it seemed like too much - and I thought it wiser to start small. 

It needs a version git tag for the version before it's consumable by the public, but I'd like it to be at some form of completeness before then. 

Tagging @alex @plusjeff @awong-dev in case they have thoughts, feelings, or insights.

**Comment by dannychapman** [comment]
@emilyville Awesome! Thanks for stubbing this out. Next week. Agreed 100% on starting small.

**Comment by plusjeff** [comment]
:+1:
